### ISSUE TITLE
styled.global - Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet'

### ISSUE THREAD

**Issue by kolodziejczakM** [sadick254/scoped-style#27]
I wanted to use Eric Meyer's Reset CSS 2.0 so I've copied the code from https://cssreset.com/scripts/eric-meyer-reset-css/ and assigned to global, like this:

```
styled.global`
    /* http://meyerweb.com/eric/tools/css/reset/ 
   v2.0 | 20110126
   License: none (public domain)
*/

    html,
    body,
    div,
    span,
    applet,
    object,
    iframe,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    p,
    blockquote,
    pre,
    a,
    abbr,
    acronym,
    address,
    big,
    cite,
    code,
    del,
    dfn,
    em,
    img,
    ins,
    kbd,
    q,
    s,
    samp,
    small,
    strike,
    strong,
    sub,
    sup,
    tt,
    var,
    b,
    u,
    i,
    center,
    dl,
    dt,
    dd,
    ol,
    ul,
    li,
    fieldset,
    form,
    label,
    legend,
    table,
    caption,
    tbody,
    tfoot,
    thead,
    tr,
    th,
    td,
    article,
    aside,
    canvas,
    details,
    embed,
    figure,
    figcaption,
    footer,
    header,
    hgroup,
    menu,
    nav,
    output,
    ruby,
    section,
    summary,
    time,
    mark,
    audio,
    video {
        margin: 0;
        padding: 0;
        border: 0;
        font-size: 100%;
        font: inherit;
        vertical-align: baseline;
    }
    /* HTML5 display-role reset for older browsers */
    article,
    aside,
    details,
    figcaption,
    figure,
    footer,
    header,
    hgroup,
    menu,
    nav,
    section {
        display: block;
    }
    body {
        line-height: 1;
    }
    ol,
    ul {
        list-style: none;
    }
    blockquote,
    q {
        quotes: none;
    }
    blockquote:before,
    blockquote:after,
    q:before,
    q:after {
        content: '';
        content: none;
    }
    table {
        border-collapse: collapse;
        border-spacing: 0;
    }
`;
```
Unfortunately I got a following error:
```

Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule ',
    p,
    blockquote,
    pre,
    a,
    abbr,
    acronym,
    address,
    big,
    cite,
    code,
    del,
    dfn,
    em,
    img,
    ins,
    kbd,
    q,
    s,
    samp,
    small,
    strike,
    strong,
    sub,
    sup,
    tt,
    var,
    b,
    u,
    i,
    center,
    dl,
    dt,
    dd,
    ol,
    ul,
    li,
    fieldset,
    form,
    label,
    legend,
    table,
    caption,
    tbody,
    tfoot,
    thead,
    tr,
    th,
    td,
    article,
    aside,
    canvas,
    details,
    embed,
    figure,
    figcaption,
    footer,
    header,
    hgroup,
    menu,
    nav,
    output,
    ruby,
    section,
    summary,
    time,
    mark,
    audio,
    video {
        margin: 0;
        padding: 0;
        border: 0;
        font-size: 100%;
        font: inherit;
        vertical-align: baseline;
    }'.
    at n (webpack:///./node_modules/scoped-style/dist/scoped-style.js?:1:984)
    at Function.e.global (webpack:///./node_modules/scoped-style/dist/scoped-style.js?:1:2393)
    at eval (webpack:///./src/styles.ts?:9:15)
    at Object../src/styles.ts (http://localhost:8080/bundle.js:1391:1)
    at __webpack_require__ (http://localhost:8080/bundle.js:727:30)
    at fn (http://localhost:8080/bundle.js:101:20)
    at eval (webpack:///./src/index.tsx?:7:1)
    at Object../src/index.tsx (http://localhost:8080/bundle.js:1343:1)
    at __webpack_require__ (http://localhost:8080/bundle.js:727:30)
    at fn (http://localhost:8080/bundle.js:101:20)
```

**Comment by halcaponey** [comment]
After investigation it seems that `h1, h2, h3, h4, h5, h6,` are not matched by the regex since they contain numbers.

**Comment by timonson** [comment]
You can fix it by changing `var globalRuleRegex = /[a-z\*,\s]+\s\{\W+[:;#%\/\\\.\(\)\+,\s\w"'-]+\}/gm` to `var globalRuleRegex = /[a-z0-9\*,\s]+\s\{\W+[:;#%\/\\\.\(\)\+,\s\w"'-]+\}/gm` in utils.js I believe.

**Comment by halcaponey** [comment]
Working on this at the moment, it's more complicated than I thought, will PR soon.
